
    // Page object library for 360sv
module.exports = {
    url: 'https://ads-demo-2.alpha360.app/Account/Login',
    url: 'https://dev-build-2.alpha360.app/',
    elements: {
//  login Page Objects
        WindowsBtn: {selector: '//*[@id="socialLoginList"]/p/button', locateStrategy: 'xpath'},
        UsernameInput: { selector: '//*[@id="UserName"]', locateStrategy: 'xpath'},
        PasswordInput: { selector: '//*[@id="Password"]', locateStrategy: 'xpath'},
        LoginBtn: { selector: '//*[@id="loginForm"]/div/div[4]/div/input', locateStrategy: 'xpath'},
        LoginErrorMessageOne: {selector: '//*[@id="ctl10"]', locateStrategy: 'xpath'},
        LoginErrorMessageTwo: {selector: '//*[@id="ctl12"]', locateStrategy: 'xpath'},
// Home Page Objects ------------------------------------------------------------------------------------------------------>
        HomePageBtn: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_0"]/div/div[1]', locateStrategy: 'xpath'},
        HomePageIcon: {selector: '//*[@id="form1"]/div[3]/div/div[1]/div/div[2]/a/img', locateStrategy: 'xpath'},
    // Quality and Audit
        QualityAudit: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_1"]/div/div[1]', locateStrategy: 'xpath'},
        // Input Management
        InputManagement: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_1"]/div/div[2]/a[1]', locateStrategy: 'xpath'},
            // Filter functionality
        SourceInput: {selector: '//*[@id="WideMain_tbSearchPlatForm"]', locateStrategy: 'xpath'},
        FileNameInput: {selector: '//*[@id="WideMain_tbSearchFile"]', locateStrategy: 'xpath'},
        SearchBtn: {selector: '//*[@id="WideMain_BtnSearch"]', locateStrategy: 'xpath'},
        StatusDropDown: {selector: '//*[@id="WideMain_DDL_Status"]', locateStrategy: 'xpath'},
        StatusNotDone: {selector: '//*[@id="WideMain_DDL_Status"]/option[2]', locateStrategy: 'xpath'},
        PeriodInputStart: {selector: '//*[@id="WideMain_txtDateStart"]', locateStrategy: 'xpath'},
        PeriodInputEnd: {selector: '//*[@id="WideMain_txtDateEnd"]', locateStrategy: 'xpath'},
            // Table Columns
        StatusColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[1]/a', locateStrategy: 'xpath'},
        SourceColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[2]/a', locateStrategy: 'xpath'},
        FileNameColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[3]/a', locateStrategy: 'xpath'}, 
        DataTypeColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[4]/a', locateStrategy: 'xpath'},
        DateColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[5]/a', locateStrategy: 'xpath'},
        LoadingOKColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[7]/a', locateStrategy: 'xpath'},
        LoadingRejectedColumn: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[2]/th[9]/a', locateStrategy: 'xpath'},
            // Table fields
        ActionsDropDrown: {selector: '//*[@id="WideMain_GridView1"]/tbody/tr[3]/td[15]/div/button', locateStrategy: 'xpath'},
        ReloadOption: {selector: '//*[@id="WideMain_GridView1_lbnAction_Reload_0"]', locateStrategy: 'xpath'},
        MarkDone: {selector: '//*[@id="WideMain_GridView1_lbnAction_Done_0"]', locateStrategy: 'xpath'},
        MarkNotDone: {selector: '//*[@id="WideMain_GridView1_lbnAction_NotDone_0"]', locateStrategy: 'xpath'},
        TransTypeBtn: {selector: '//*[@id="WideMain_GridView1_linkBtn_du_pnl_item_0"]', locateStrategy: 'xpath'},
        ProductsField: {selector: '//*[@id="WideMain_GridView1_lb_du_Products_0"]', locateStrategy: 'xpath'},
        ClientsField: {selector: '//*[@id="WideMain_GridView1_lb_du_Clients_0"]', locateStrategy: 'xpath'},
        StatusField: {selector: '//*[@id="WideMain_GridView1_lblStatus_0"]', locateStrategy: 'xpath'},
        SourceField: {selector: '//*[@id="WideMain_GridView1_lblPlatform_0"]', locateStrategy: 'xpath'},
        FileNameField: {selector: '//*[@id="WideMain_GridView1_lblFileName_0"]', locateStrategy: 'xpath'},
        DataTypeField: {selector: '//*[@id="WideMain_GridView1_lblContent_0"]', locateStrategy: 'xpath'},
        DateField: {selector: '//*[@id="WideMain_GridView1_lblDateStamp_0"]', locateStrategy: 'xpath'},
        LoadingOKField: {selector: '//*[@id="WideMain_GridView1_lblRecords_0"]', locateStrategy: 'xpath'},
        LoadingRejectedField: {selector: '//*[@id="WideMain_GridView1_lb_Rejected_0"]', locateStrategy: 'xpath'},
        LoadingAlertsField: {selector: '//*[@id="WideMain_GridView1_lb_Alerts_0"]', locateStrategy: 'xpath'},
            // misc 
        LoadingRejectedPopOutCloseBtn: {selector: '//*[@id="WideMain_btnCancel"]', locateStrategy: 'xpath'},
        LoadingAlertsPopOutCloseBtn: {selector: '//*[@id="WideMain_btnCancel3"]', locateStrategy: 'xpath'},
            // Transaction type edit options
        BuyAssetDropDown: {selector: '//*[@id="WideMain_GV_TABs_DDL_PL_Tab_0"]', locateStrategy: 'xpath'},
        ExcludeDD1: {selector: '//*[@id="WideMain_GV_TABs_DDL_PL_Tab_0"]/option[1]', locateStrategy: 'xpath'},
        TransTypeSaveBtn: {selector: '//*[@id="WideMain_btnPnLSave"]', locateStrategy: 'xpath'},
        TransTypeCloseBtn: {selector: '//*[@id="WideMain_btnClose5"]', locateStrategy: 'xpath'},
        TransTypeConfirmBtn: {selector: '//*[@id="WideMain_thePopMsg_ok"]', locateStrategy: 'xpath'},
        // Audit Trail
        AuditTrail: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_1"]/div/div[2]/a[2]', locateStrategy: 'xpath'},
        AuditTrailSubBar: {selector: '//*[@id="ctl14_menu1_subNavBar_divSubItem_1"]/a', locateStrategy: 'xpath'},
        SourceDropDown2: {selector: '//*[@id="WideMain_LBSource"]/option[2]', locateStrategy: 'xpath'},
        DateInputStart: {selector: '//*[@id="WideMain_tb_StartDate"]', locateStrategy: 'xpath'},
        DateInputEnd: {selector: '//*[@id="WideMain_tb_EndDate"]', locateStrategy: 'xpath'},
        PNLItemDropDown4: {selector: '//*[@id="WideMain_LBPnLItem"]/option[4]', locateStrategy: 'xpath'},
        ClientSourceNameInput: {selector: '//*[@id="WideMain_txtSearch"]', locateStrategy: 'xpath'},
        ClientTargetNameInput: {selector: '//*[@id="WideMain_tbTargetClientSearch"]', locateStrategy: 'xpath'},
        ProductSourceNameInput: {selector: '//*[@id="WideMain_txtSearchProduct"]', locateStrategy: 'xpath'},
        ProductTargetNameInput: {selector: '//*[@id="WideMain_tbTargetProductSearch"]', locateStrategy: 'xpath'},
    // Client Management
        ClientManagement: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_2"]/div/div[1]', locateStrategy: 'xpath'},
        // Client Matching
        ClientMatching: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_2"]/div/div[2]/a[1]', locateStrategy: 'xpath'},
        PendingMatch: {selector: '//*[@id="WideMain_GridView1_lbl_account_name_0"]', locateStrategy: 'xpath'},
        CMStatusDropDown: {selector: '//*[@id="WideMain_DDL_Match"]', locateStrategy: 'xpath'},
        CMStatusUnmatched: {selector: '//*[@id="WideMain_DDL_Match"]/option[3]', locateStrategy: 'xpath'},
        CMStatusPending: {selector: '//*[@id="WideMain_DDL_Match"]/option[4]', locateStrategy: 'xpath'},
        CMSourceInput: {selector: '//*[@id="WideMain_tbSearchSourceAccount"]', locateStrategy: 'xpath'},
        CMTargetClientInput: {selector: '//*[@id="WideMain_tbSearchTargetClient"]', locateStrategy: 'xpath'},
        CMSourcePostalInput: {selector: '//*[@id="WideMain_tbSearchSourceZIP"]', locateStrategy: 'xpath'},
        CMTargetPostalInput: {selector: '//*[@id="WideMain_tbSearchTargetZIP"]', locateStrategy: 'xpath'},
        CMPendingApproveBtn: {selector: '//*[@id="WideMain_GridView1_btnApprove_0"]', locateStrategy: 'xpath'},
        CMPendingDenyBtn: {selector: '//*[@id="WideMain_GridView1_btnDeny_0"]', locateStrategy: 'xpath'},
        CMTakeBtn: {selector: '//*[@id="WideMain_GridView1_btnTakeLine_1"]', locateStrategy: 'xpath'},
        CMDenyBtn: {selector:'//*[@id="WideMain_GridView1_btnDeny_0"]', locateStrategy: 'xpath'},
        CMSaveBtn: {selector: '//*[@id="WideMain_btnSaveTake"]', locateStrategy: 'xpath'},
        CMSaveBtn2: {selector: '//*[@id="WideMain_btnSaveApprove"]', locateStrategy: 'xpath'},
    // Product Management
        ProductManagement: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_3"]/div/div[1]', locateStrategy: 'xpath'},
        // Product Matching
        ProductMatching: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_3"]/div/div[2]/a', locateStrategy: 'xpath'},
        PMStatusDropDown: {selector: '//*[@id="WideMain_DDL_Filter"]', locateStrategy: 'xpath'},
        PMStatusUnmatched: {selector: '//*[@id="WideMain_DDL_Filter"]/option[1]', locateStrategy: 'xpath'},
        PMProductInput: {selector: '//*[@id="WideMain_txtSearch2"]', locateStrategy: 'xpath'},
        PMProductName: {selector: '//*[@id="WideMain_GridView1_lbl_source_product_name_4"]', locateStrategy: 'xpath'},
        PMEditBtn: {selector: '//*[@id="WideMain_btnEdit"]', locateStrategy: 'xpath'},
        PMTakeBtn: {selector: '//*[@id="WideMain_btnSafeProduct"]', locateStrategy: 'xpath'},
        PMSaveBtn: {selector: '//*[@id="WideMain_BntSafeUpate"]', locateStrategy: 'xpath'},
        PMCloseBtn: {selector: '//*[@id="WideMain_btnCancel"]', locateStrategy: 'xpath'},
        PMDenyBtn: {selector: '//*[@id="WideMain_GridView1_btnDeny_4"]', locateStrategy: 'xpath'},
        PMDenyBtn2: {selector: '//*[@id="WideMain_GridView1_btnDeny_5"]', locateStrategy: 'xpath'},
        PMDenyBtn3: {selector: '//*[@id="WideMain_GridView1_btnDeny_6"]', locateStrategy: 'xpath'},
        PMOKBtn: {selector: '//*[@id="WideMain_btnDenyOK"]', locateStrategy: 'xpath'},
            // Config Objects --------------------------------------------------------------------------------------------------------->
        ProjectSelect: {selector: '//*[@id="project_select"]/option[2]', locateStrategy: 'xpath'},
        // Provider List
        ProviderList: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_1"]/div/div[2]/a[5]', locateStrategy: 'xpath'},
        PLActionBtn: {selector: '//*[@id="Main_GridView1"]/tbody/tr[2]/td[5]/div/button', locateStrategy: 'xpath'},
        PLEditBtn: {selector: '//*[@id="Main_GridView1_lbnAction_Edit_0"]', locateStrategy: 'xpath'},
        PLAddBtn: {selector: '//*[@id="WideMain_gridOmnibusAccounts_btnAddOmnibusAccount"]', locateStrategy: 'xpath'},
        OmnibusAccDropDown: {selector: '//*[@id="WideMain_ddlAddOmnibusAccountProvider"]', locateStrategy: 'xpath'},
        SevenIMOption: {selector: '//*[@id="WideMain_ddlAddOmnibusAccountProvider"]/option[1]', locateStrategy: 'xpath'},
        AegonOption: {selector: '//*[@id="WideMain_ddlAddOmnibusAccountProvider"]/option[2]', locateStrategy: 'xpath'},
        PLValidateBtn: {selector: '//*[@id="WideMain_addOmnibusAccountValidate"]', locateStrategy: 'xpath'},
        PLSaveBtn: {selector: '//*[@id="WideMain_btnSaveOmnibusAccount"]', locateStrategy: 'xpath'},
        PLEditSaveBtn: {selector: '//*[@id="WideMain_btnSaveData"]', locateStrategy: 'xpath'},
        DefaultUnmatchedInput: {selector: '//*[@id="WideMain_txtUnmatched"]', locateStrategy: 'xpath'},
        DefaultUnmatchedErrorMessage: {selector: '//*[@id="WideMain_rfvUnmatched"]', locateStrategy: 'xpath'},
        DefaultUnmatchedErrorMessage2: {selector: '//*[@id="WideMain_cvUnmatched"]', locateStrategy: 'xpath'},
        DefaultTrueUpInput: {selector: '//*[@id="WideMain_txtDefaultTrueUp"]', locateStrategy: 'xpath'},
        DefaultTrueUpErrorMessage: {selector: '//*[@id="WideMain_rfvDefaultTrueUp"]', locateStrategy: 'xpath'},
        DefaultTrueUpErrorMessage2: {selector: '//*[@id="WideMain_cvDefaultTrueUp"]', locateStrategy: 'xpath'},
    // Settings
        Settings: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_5"]/div/div[1]', locateStrategy: 'xpath'},
        // Manage Account
        ManageAccount: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_5"]/div/div[2]/a[1]', locateStrategy: 'xpath'},
        ChangeBtn: {selector: '//*[@id="Main_ChangePassword"]', locateStrategy: 'xpath'},
        NewPasswordInput: {selector: '//*[@id="Main_NewPassword"]', locateStrategy: 'xpath'},
        ConfirmNewPasswordInput: {selector: '//*[@id="Main_ConfirmNewPassword"]', locateStrategy: 'xpath'},
        ChangePasswordBtn: {selector: '//*[@id="passwordForm"]/div/div[4]/div/input', locateStrategy: 'xpath'},
        ChangePasswordMessage: {selector: '//*[@id="form1"]/div[5]/div/div/div[1]/p', locateStrategy: 'xpath'},
    // Production
        Production: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_4"]/div/div[1]', locateStrategy: 'xpath'},
        // Processing Queue
        ProcessingQueue: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_4"]/div/div[2]/a[2]', locateStrategy: 'xpath'},
        JobsQueue: {selector: '//*[@id="form1"]/div[5]/div[2]/div/div[1]/div[1]/h2', locateStrategy: 'xpath'},
        JobCancel: {selector: '//*[@id="WideMain_gvJobs_btnCancel_0"]', locateStrategy: 'xpath'},
        // Fiscal Period Management
        FiscalPeriod: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_4"]/div/div[2]/a[1]', locateStrategy: 'xpath'},
        FiscalDateCalendar: {selector: '//*[@id="Main_calendar"]/tbody/tr[3]/td[7]/a', locateStrategy: 'xpath'},
        FPClosePeriodSaveBtn: {selector: '//*[@id="Main_btnClosePeriod"]', locateStrategy: 'xpath'},
        FPReopenPeriodSaveBtn: {selector: '//*[@id="Main_btnReopenPeriod"]', locateStrategy: 'xpath'},
        FPConfirmReOpSave: {selector: '//*[@id="Main_btnReopenSave"]', locateStrategy: 'xpath'},
        FPConfirmReOpCancel: {selector: '//*[@id="view-period-dialog"]/div/div/div[3]/div/button', locateStrategy: 'xpath'},
        FPConfirmCloseSave: {selector: '//*[@id="Main_btnClosePeriod"]', locateStrategy: 'xpath'},
        FPConfirmCloseCancel: {selector: '//*[@id="close-period-dialog"]/div/div/div[3]/div/button', locateStrategy: 'xpath'},
        FPClosePeriodCancelBtn: {selector: '//*[@id="close-period-dialog"]/div/div/div[3]/div/button', locateStrategy: 'xpath'},
        FPReopenPeriodCancelBtn: {selector: '//*[@id="view-period-dialog"]/div/div/div[3]/div/button', locateStrategy: 'xpath'},
        CommentBoxClose: {selector: '//*[@id="Main_txtPeriodCloseComments"]', locateStrategy: 'xpath'},
        CommentBoxReOp: {selector: '//*[@id="Main_txtReopenComments"]', locateStrategy: 'xpath'},
        SelectDatePeriod: {selector: '//*[@id="Main_txtSelectedDate"]', locateStrategy: 'xpath'},
    // Jobs
        Jobs: {selector: '//*[@id="ctl14_menu1_navBar_divMenuItem_4"]/div/div[2]/a[3]', locateStrategy: 'xpath'},
        //Rescan Input Directory
        RescanInputDirectory: {selector: '//*[@id="Main_rptJobTypes_lbn_0"]', locateStrategy: 'xpath'},
        //Upload sources
        UploadSources: {selector: '//*[@id="Main_rptJobTypes_lbn_1"]', locateStrategy: 'xpath'},
        //Backend Run
        BackendRun: {selector: '//*[@id="Main_rptJobTypes_lbn_2"]', locateStrategy: 'xpath'},
        //Generate Client Matches
        GenerateClientMatches: {selector: '//*[@id="Main_rptJobTypes_lbn_3"]', locateStrategy: 'xpath'},
        //Full Run
        FullRun: {selector: '//*[@id="Main_rptJobTypes_lbn_4"]', locateStrategy: 'xpath'},
        //Job queue status
        RunASAP: {selector: '//*[@id="Main_btnRunAsap"]', locateStrategy: 'xpath'},
        AddToQueue: {selector: '//*[@id="Main_btnQueue"]', locateStrategy: 'xpath'},
        AddToSchedule: {selector: '//*[@id="Main_btnSchedule"]', locateStrategy: 'xpath'},
        cancelJob: {selector: '//*[@id="WideMain_gvJobs_btnDelete_0"]', locateStrategy: 'xpath'},
        StartDate: {selector: '//*[@id="Main_txtDateStart"]', locateStrategy: 'xpath'},
        EndDate: {selector: '//*[@id="Main_txtDateEnd"]', locateStrategy: 'xpath'},
        RunJob: {selector: '//*[@id="Main_btnSaveDate"]', locateStrategy: 'xpath'},
        }
}